#!/usr/bin/env python3
"""
SkillForge Hook: Infrastructure File Protection (PreToolUse: Edit|Write|MultiEdit)

Reads the tool_input from stdin and blocks any edit whose target file matches
a critical path for the current project. The list of critical paths is read
from .claude/project-profile.json (generated by hooks/detect.sh), so protection
adapts automatically to the detected stack — WordPress gets wp-config.php, a
Laravel app gets artisan and config/app.php, a Go tool gets go.mod, and so on.

If no profile is found we fall back to a minimal universal list covering the
files that are dangerous on any project (env vars, lockfiles, Docker, CI).
"""

import json
import os
import sys

FALLBACK_CRITICAL = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.staging",
    ".env.development",
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    ".github/workflows",
    ".gitlab-ci.yml",
    "Jenkinsfile",
    "package.json",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "composer.json",
    "composer.lock",
    "Cargo.lock",
    "go.sum",
]


def load_critical_files(project_dir: str) -> list:
    """Read critical_files from project profile, or return fallback."""
    profile_path = os.path.join(project_dir, ".claude", "project-profile.json")
    try:
        with open(profile_path) as f:
            profile = json.load(f)
        files = profile.get("critical_files") or []
        if isinstance(files, list) and files:
            return files
    except (OSError, json.JSONDecodeError, ValueError):
        pass
    return FALLBACK_CRITICAL


def normalize(path: str) -> str:
    """Normalize to forward slashes, strip leading './' and multiple slashes."""
    norm = path.replace("\\", "/").strip()
    while norm.startswith("./"):
        norm = norm[2:]
    # Ensure a leading slash so suffix matches are anchored to a path boundary
    if not norm.startswith("/"):
        norm = "/" + norm
    while "//" in norm:
        norm = norm.replace("//", "/")
    return norm


def match_critical(file_path: str, critical_files: list):
    """Return the matching critical entry, or None."""
    norm = normalize(file_path)
    for crit in critical_files:
        if not crit:
            continue
        c = crit.replace("\\", "/").strip("/")
        if not c:
            continue
        file_needle = "/" + c
        dir_needle = "/" + c + "/"
        # Exact file match (path ends with "/<critical>") or directory
        # containment (path has "/<critical>/" somewhere).
        if norm.endswith(file_needle) or dir_needle in (norm + "/"):
            return crit
    return None


def reason_for(match: str) -> str:
    """Short human-readable reason for the block."""
    low = match.lower()
    if ".env" in low:
        return "Environment file — may contain secrets"
    if "lock" in low or low in ("go.sum",):
        return "Lockfile — affects build reproducibility"
    if "docker" in low:
        return "Container configuration — affects deployment"
    if "workflow" in low or "gitlab-ci" in low or "jenkinsfile" in low:
        return "CI/CD pipeline — affects automation"
    if "wp-config" in low or ".htaccess" in low:
        return "WordPress infrastructure file"
    if low.endswith(".json") or low.endswith(".toml") or low.endswith(".yaml") or low.endswith(".yml"):
        return "Project manifest — affects all builds"
    if "middleware" in low or "layout" in low:
        return "Runs on every request / page — wide blast radius"
    return "Infrastructure file — wide impact"


def main() -> None:
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        sys.exit(0)

    if data.get("tool_name") not in ("Edit", "Write", "MultiEdit"):
        sys.exit(0)

    tool_input = data.get("tool_input") or {}
    file_path = tool_input.get("file_path") or tool_input.get("path") or ""
    if not file_path or not isinstance(file_path, str):
        sys.exit(0)

    project_dir = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    critical_files = load_critical_files(project_dir)

    match = match_critical(file_path, critical_files)
    if match is None:
        sys.exit(0)

    sys.stderr.write(
        "🚨 PROTECTED FILE (SkillForge guard)\n"
        f"File: {file_path}\n"
        f"Matched pattern: {match}\n"
        f"Reason: {reason_for(match)}\n\n"
        "This file is listed in .claude/project-profile.json as critical for\n"
        "the detected stack. Explain WHAT you want to change and WHY, and wait\n"
        "for the user to approve before retrying.\n"
    )
    sys.exit(2)


if __name__ == "__main__":
    main()
